version: '3.3'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - ./log:/var/log/nginx

  nodejs:
    build: ./nodejs
    container_name: nodejs




